# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f70920202e4848853da06964f2db07555f1f9b99ba57b09841e84ab4363a76f5ec483777fe9813784249b2b809833386bc171f022dace055890b448be52ed3a5

test:
  secret_key_base: 47e455fe4998c1203977d18e654c49aaecd00bb9298f3c8c61598f4a2e4b5c8b15e76fb57691382f504c409c875aebb9b0a4e645d08df5a349a24c8486a1ff1e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
